<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Define Xacro properties -->
    <xacro:property name="camera_l" value="0.01" />
    <xacro:property name="camera_w" value="0.1" />
    <xacro:property name="camera_h" value="0.05" />
    <xacro:property name="base_l" value="1.0" />
    <xacro:property name="base_h" value="0.3" />
    
    <!-- Camera Link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_l} ${camera_w} ${camera_h}" />
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_l} ${camera_w} ${camera_h}" />
            </geometry>
        </collision>
        <xacro:box_inertia mass="0.1" l="${camera_l}" w="${camera_w}" h="${camera_h}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!-- Joint connecting base_link to camera_link -->
    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_l + camera_l) / 2.0} 0 ${(base_h / 2.0) - (camera_h / 2.0)}" rpy="0 0 0" />
    </joint>

    <!-- Camera Optical Link -->
    <link name="camera_link_optical" />

    <!-- Joint connecting camera_link to camera_link_optical -->
    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link" />
        <child link="camera_link_optical" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    </joint>

    <!-- Gazebo Plugin (commented out correctly) -->
    
    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <camera>
                <horizontal_fov>1.047</horizontal_fov>
                <image>
                    <format>B8G8R8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>
   
</robot>

